usr_type_num: 8
usr_emb_dim: 128
#usr_feature_dim: 40
usr_feature_dim: 34
#category_num: 19
#category_num: 17
category_num: 10
category_emb_dim: 128
hour_emb_dim: 32
week_emb_dim: 32
hidden_size: 256
rnn_layers: 4
dropout: 0.1

lr: 1.0e-5
epoch_num: 1000
batch_size: 64
#batch_size: 1

dur_weight: 20.0
dist_weight: 20.0

#dur_weight: 0.0
#dist_weight: 0.0

max_norm: 1.0
norm_type: 2.0
